url: "https://blog.liamcottle.com"
baseurl: ""
title: "Liam Cottle's Blog"
subtitle: "🇳🇿 New Zealand"
description: "Rambles from a self taught Software Engineer"
image: "assets/images/avatar.jpg"
permalink: ":year/:month/:day/:title"

author:
  name: "Liam Cottle"
  avatar: "assets/images/avatar.jpg"

intro:
  title: "Hey there 👋"
  description: |
    Welcome to my blog. I write about software, hardware, security vulnerabilities and anything else I find interesting.
    Hopefully you'll find something that interests you too. Feel free to explore my postings!

# social links
discord_url: "https://discord.gg/APQSQZNV7t"
github_url: "https://github.com/liamcottle"
twitter_url: "https://twitter.com/liamcottle"
contact_url: "https://liamcottle.com/contact"
linkedin_url: "https://www.linkedin.com/in/liamcottle/"
paypal_url: "https://paypal.me/liamcarncottle"

# analytics
google_analytics_measurement_id: "G-S3724X6D5M"
hitsteps_tracking_id: "d3f1847a76c4933f532da4ae84a36a0be183b"

plugins:
  - jekyll-feed
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - vendor
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
